# Generated by Django 3.2 on 2021-05-12 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('net_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatDialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user_first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_sender', to=settings.AUTH_USER_MODEL)),
                ('user_second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
