# Generated by Django 3.2 on 2021-05-12 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('net_app', '0002_chatdialog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatdialog',
            old_name='user_second',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='chatdialog',
            old_name='user_first',
            new_name='sender',
        ),
    ]
