# Generated by Django 3.2 on 2021-04-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('net_app', '0002_auto_20210423_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='page_name',
            new_name='poster',
        ),
    ]
