# Generated by Django 3.2 on 2021-04-23 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('net_app', '0003_rename_page_name_post_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='poster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment_poster', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentpost',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
