# Generated by Django 3.2 on 2021-05-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_app', '0003_auto_20210512_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatdialog',
            name='message',
            field=models.TextField(),
        ),
    ]
