# Generated by Django 3.2 on 2021-04-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_app', '0004_auto_20210420_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='comment',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Комментарий'),
        ),
    ]
